
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author John Herrold
 */
public class PETA2 extends javax.swing.JFrame {

    private Object v;

    /**
     * Creates new form PETA2
     */
    public PETA2() {            
        

        
        initComponents();
    }
    
    public int index(){
        
        return index;
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtUser1 = new javax.swing.JTextField();
        rbtnAdd = new javax.swing.JRadioButton();
        rbtnUpd = new javax.swing.JRadioButton();
        rbtnDel = new javax.swing.JRadioButton();
        txtPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        txtFeedback = new javax.swing.JTextField();
        txta = new javax.swing.JScrollPane();
        txtaAll = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbtnAdd);
        rbtnAdd.setLabel("Add");
        rbtnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnAddMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbtnUpd);
        rbtnUpd.setLabel("Update");
        rbtnUpd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnUpdMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbtnDel);
        rbtnDel.setText("Delete");
        rbtnDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnDelMouseClicked(evt);
            }
        });

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        btnDone.setText("OK");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        txtFeedback.setEditable(false);

        txtaAll.setEditable(false);
        txtaAll.setColumns(20);
        txtaAll.setRows(5);
        txta.setViewportView(txtaAll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDone)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtPass)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnUpd)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnDel)))
                .addGap(18, 18, 18)
                .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnAdd)
                            .addComponent(rbtnUpd)
                            .addComponent(rbtnDel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(btnDone)
                        .addGap(18, 18, 18)
                        .addComponent(txtFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        
        String pass, user;
        
        user = txtUser.getText();
        pass = txtPass.getText();
        
        ArrayList users = new ArrayList(32);
        ArrayList passes = new ArrayList(32);
        
        int index = users.indexOf(user);
        int index2 = passes.indexOf(pass);
        
        Object gs = evt.getSource();    
                
        if(user.equals(pass)){
            txtFeedback.setText("");
            txtFeedback.setText("User and pass must not be the same!");
        }else if(user.equals("")){
            txtFeedback.setText("");
            txtFeedback.setText("User can't be blank!");
        }else if(index != -1){
            txtFeedback.setText("");
            txtFeedback.setText("User already exist!");
        }else{
            txtFeedback.setText("");
            txtFeedback.setText("Contact added!");
            users.add(user);
            passes.add(pass);
            txtaAll.append("\n" + user + "   " + pass);
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    private void rbtnUpdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnUpdMouseClicked
        Object upd = evt.getSource();
    }//GEN-LAST:event_rbtnUpdMouseClicked

    private void rbtnDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnDelMouseClicked
        Object del = evt.getSource();
        
    }//GEN-LAST:event_rbtnDelMouseClicked

    private void rbtnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnAddMouseClicked
        Object add = evt.getSource();
    }//GEN-LAST:event_rbtnAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PETA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PETA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PETA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PETA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PETA2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbtnAdd;
    private javax.swing.JRadioButton rbtnDel;
    private javax.swing.JRadioButton rbtnUpd;
    private javax.swing.JTextField txtFeedback;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUser1;
    private javax.swing.JScrollPane txta;
    private javax.swing.JTextArea txtaAll;
    // End of variables declaration//GEN-END:variables
}
